export const spe = [
  "CyanoPV",
  "OwensPV",
  "TakiPV",
  "S&F Building, LLC",
  "Kula AG-FIT",
  "T10PV",
  "T13",
  "T15",
  "T18",
  "T20",
  "Notre Dame PV",
  "Hilo Hotel PV",
  "PR Outlet PV",
  "Wyndham - Angels Camp",
  "Wyndham - Bass Lake",
  "Wyndham - Big Bear",
  "Mission Valley PV - Wyndham Indio",
  "Wyndham - Kihei",
  "Wyndham - Kona",
  "Mission Valley PV",
  "Wyndham - Rancho Vistoso",
  "Wyndham Solvang",
  "Wyndham - Windsor Carport",
  "Wyndham - Windsor Rooftop",
  "Zurn",
  "PGE - St Louis",
  "PGE - Thomas Creek",
  "PGE - Tickle Creek",
  "PGE - Volcano",
  "PGE - Dunn Rd",
  "PGE - Mt Hope",
  "PGE - Williams Acres",
  "PGE - River Valley",
  "Green Bridge",
  "Kawela Deep Well 1",
  "CCND - Newman Hall",
  "CCND - Mayaguez",
  "Glory Nani Mau",
  "AOAO Pearl Horizons",
  "Redstone",
];
