export const spe = [
  "CyanoPV",
  "OwensPV",
  "TakiPV",
  "S&F Building, LLC",
  "Kula AG-FIT",
  "T10PV",
  "T13",
  "T15",
  "T18",
  "T20",
  "Notre Dame PV",
  "Hilo Hotel PV",
  "PR Outlet PV",
  "Wyndham - Angels Camp",
  "Wyndham - Bass Lake",
  "Wyndham - Big Bear",
  "Mission Valley PV - Wyndham Indio",
  "Wyndham - Kihei",
  "Wyndham - Kona",
  "Mission Valley PV",
  "Wyndham - Rancho Vistoso",
  "Wyndham Solvang",
  "Wyndham - Windsor Carport",
  "Wyndham - Windsor Rooftop",
  "Zurn",
  "PGE - St Louis",
  "PGE - Thomas Creek",
  "PGE - Tickle Creek",
  "PGE - Volcano",
  "PGE - Dunn Rd",
  "PGE - Mt Hope",
  "PGE - Williams Acres",
  "PGE - River Valley",
  "Green Bridge",
  "Kawela Deep Well 1",
  "CCND - Newman Hall",
  "CCND - Mayaguez",
  "Glory Nani Mau",
  "AOAO Pearl Horizons",
  "Redstone",
];
export const tags = [
  "CyanoPV",
  "OwensPV",
  "TakiPV",
  "S&F Building, LLC",
  "Kula AG-FIT",
  "T10PV",
  "T13",
  "T15",
  "T18",
  "T20",
  "Notre Dame PV",
  "Hilo Hotel PV",
  "PR Outlet PV",
  "Wyndham",
  "Mission Valley PV",
  "Zurn",
  "PGE",
  "Green Bridge",
  "Kawela Deep Well 1",
  "CCND",
  "Glory Nani Mau",
  "AOAO Pearl Horizons",
  "Redstone",
];
export const issues = [
  {
    name: "Install new panel",
    type: "Broken Panel",
    priority: "High",
    assigned_by: "Joe Hobbs",
    assigned_to: "Barry Oswald",
    running_clock: "5.3"
  },
  {
    name: "Fix the breakers",
    type: "System Repair",
    priority: "Medium",
    assigned_by: "Joe Hobbs",
    assigned_to: "Larry Smith",
    running_clock: "3.4"
  },
  {
    name: "Site inspection",
    type: "Routine Maintenance",
    priority: "Medium",
    assigned_by: "Joe Hobbs",
    assigned_to: "Barry Oswald",
    running_clock: "12.9"
  },
  {
    name: "Install new panel",
    type: "Broken Panel",
    priority: "High",
    assigned_by: "Joe Hobbs",
    assigned_to: "Barry Oswald",
    running_clock: "5.3"
  },
  {
    name: "Fix the breakers",
    type: "System Repair",
    priority: "Medium",
    assigned_by: "Joe Hobbs",
    assigned_to: "Larry Smith",
    running_clock: "3.4"
  },
  {
    name: "Site inspection",
    type: "Routine Maintenance",
    priority: "Medium",
    assigned_by: "Joe Hobbs",
    assigned_to: "Barry Oswald",
    running_clock: "12.9"
  }
]